#Define the stages of the pipeline
image: jaft/cicd:latest

stages:
  - build
  - deploy
before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$AWS_SSH" | tr -d '\r' | ssh-add -> /dev/null # add ssh key

#  - chmod 400 "$WSL_SSH_PRIVATE_KEY"
#  - ssh-add "$WSL_SSH_PRIVATE_KEY"
#  - mkdir -p ~/.ssh
#  - chmod 700 ~/.ssh

# Define job for building Docker image
build_image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - cd nodejssam && docker build -t jaft/my-node:e .  
    - docker build -t jaft/my-node:e .
    - docker login -u jaft -p justafool
    - docker push jaft/my-node:e

# Define job for deploying (optional)
deploy:
  stage: deploy
  script:
    # Add deployment commands here
  #  - echo "$UB_SSH_PRIVATE_KEY" | tr -d '\r' > id_rsa # add ssh key
#    - echo "$UB_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -> /dev/null # add ssh ke 
   #- ssh-add $UB_SSH_PRIVATE_KEY
   #- chmod 600 id_rsa
    - ssh ubuntu@52.20.110.27 -t  "cd /home/ubuntu && bash d.sh"

  only:
    - main  # Only deploy from the main branch (adjust as needed)

